//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.
// Licensed under Apache 2.0

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package openapi

import (
	common "k8s.io/kube-openapi/pkg/common"
	spec "k8s.io/kube-openapi/pkg/validation/spec"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./openapi.Funghus":           schema__openapi_Funghus(ref),
		"./openapi.FunghusProperties": schema__openapi_FunghusProperties(ref),
		"./openapi.GenericOrganism":   schema__openapi_GenericOrganism(ref),
		"./openapi.Person":            schema__openapi_Person(ref),
	}
}

func schema__openapi_Funghus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Funghus",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"Name": {
						SchemaProps: spec.SchemaProps{
							Default: "",
							Type:    []string{"string"},
							Format:  "",
						},
					},
					"Properties": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("./openapi.FunghusProperties"),
						},
					},
				},
				Required: []string{"Name", "Properties"},
			},
		},
		Dependencies: []string{
			"./openapi.FunghusProperties"},
	}
}

func schema__openapi_FunghusProperties(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FunghusProperties",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"Typ": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("ocm.software/open-component-model/bindings/go/runtime.Type"),
						},
					},
					"Size": {
						SchemaProps: spec.SchemaProps{
							Default: 0,
							Type:    []string{"integer"},
							Format:  "int32",
						},
					},
					"Softness": {
						SchemaProps: spec.SchemaProps{
							Default: "",
							Type:    []string{"string"},
							Format:  "",
						},
					},
				},
				Required: []string{"Typ", "Size", "Softness"},
			},
		},
		Dependencies: []string{
			"ocm.software/open-component-model/bindings/go/runtime.Type"},
	}
}

func schema__openapi_GenericOrganism(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GenericOrganism",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"Name": {
						SchemaProps: spec.SchemaProps{
							Default: "",
							Type:    []string{"string"},
							Format:  "",
						},
					},
					"Properties": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("ocm.software/open-component-model/bindings/go/runtime.Raw"),
						},
					},
				},
				Required: []string{"Name", "Properties"},
			},
		},
		Dependencies: []string{
			"ocm.software/open-component-model/bindings/go/runtime.Raw"},
	}
}

func schema__openapi_Person(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Person",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Default: "",
							Type:    []string{"string"},
							Format:  "",
						},
					},
					"age": {
						SchemaProps: spec.SchemaProps{
							Default: 0,
							Type:    []string{"integer"},
							Format:  "int32",
						},
					},
				},
				Required: []string{"name", "age"},
			},
		},
	}
}
