// Code generated by controller-gen-v0.20. DO NOT EDIT.

package applyconfiguration

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1alpha1 "ocm.software/open-component-model/kubernetes/controller/api/v1alpha1"
	apiv1alpha1 "ocm.software/open-component-model/kubernetes/controller/api/v1alpha1/applyconfiguration/api/v1alpha1"
	internal "ocm.software/open-component-model/kubernetes/controller/api/v1alpha1/applyconfiguration/internal"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=delivery.ocm.software, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Component"):
		return &apiv1alpha1.ComponentApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ComponentInfo"):
		return &apiv1alpha1.ComponentInfoApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ComponentSpec"):
		return &apiv1alpha1.ComponentSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ComponentStatus"):
		return &apiv1alpha1.ComponentStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DeployedObjectReference"):
		return &apiv1alpha1.DeployedObjectReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Deployer"):
		return &apiv1alpha1.DeployerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DeployerSpec"):
		return &apiv1alpha1.DeployerSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("DeployerStatus"):
		return &apiv1alpha1.DeployerStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Label"):
		return &apiv1alpha1.LabelApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MergeAlgorithmSpecification"):
		return &apiv1alpha1.MergeAlgorithmSpecificationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NamespacedObjectKindReference"):
		return &apiv1alpha1.NamespacedObjectKindReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectKey"):
		return &apiv1alpha1.ObjectKeyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OCMConfiguration"):
		return &apiv1alpha1.OCMConfigurationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Repository"):
		return &apiv1alpha1.RepositoryApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RepositorySpec"):
		return &apiv1alpha1.RepositorySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RepositoryStatus"):
		return &apiv1alpha1.RepositoryStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Resource"):
		return &apiv1alpha1.ResourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ResourceID"):
		return &apiv1alpha1.ResourceIDApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ResourceInfo"):
		return &apiv1alpha1.ResourceInfoApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ResourceReference"):
		return &apiv1alpha1.ResourceReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ResourceSpec"):
		return &apiv1alpha1.ResourceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ResourceStatus"):
		return &apiv1alpha1.ResourceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Verification"):
		return &apiv1alpha1.VerificationApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
