// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
)

// ComponentInfoApplyConfiguration represents a declarative configuration of the ComponentInfo type for use
// with apply.
type ComponentInfoApplyConfiguration struct {
	RepositorySpec *v1.JSON `json:"repositorySpec,omitempty"`
	Component      *string  `json:"component,omitempty"`
	Version        *string  `json:"version,omitempty"`
	// Digest information of the Component, if available as per OCM specification.
	Digest *v2.Digest `json:"digest,omitempty"`
}

// ComponentInfoApplyConfiguration constructs a declarative configuration of the ComponentInfo type for use with
// apply.
func ComponentInfo() *ComponentInfoApplyConfiguration {
	return &ComponentInfoApplyConfiguration{}
}

// WithRepositorySpec sets the RepositorySpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepositorySpec field is set to the value of the last call.
func (b *ComponentInfoApplyConfiguration) WithRepositorySpec(value v1.JSON) *ComponentInfoApplyConfiguration {
	b.RepositorySpec = &value
	return b
}

// WithComponent sets the Component field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Component field is set to the value of the last call.
func (b *ComponentInfoApplyConfiguration) WithComponent(value string) *ComponentInfoApplyConfiguration {
	b.Component = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ComponentInfoApplyConfiguration) WithVersion(value string) *ComponentInfoApplyConfiguration {
	b.Version = &value
	return b
}

// WithDigest sets the Digest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Digest field is set to the value of the last call.
func (b *ComponentInfoApplyConfiguration) WithDigest(value v2.Digest) *ComponentInfoApplyConfiguration {
	b.Digest = &value
	return b
}
