// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apiv1alpha1 "ocm.software/open-component-model/kubernetes/controller/api/v1alpha1"
)

// ComponentSpecApplyConfiguration represents a declarative configuration of the ComponentSpec type for use
// with apply.
//
// ComponentSpec defines the desired state of Component.
type ComponentSpecApplyConfiguration struct {
	// RepositoryRef is a reference to a Repository.
	RepositoryRef *v1.LocalObjectReference `json:"repositoryRef,omitempty"`
	// Component is the name of the ocm component.
	Component *string `json:"component,omitempty"`
	// DowngradePolicy specifies whether the component may be downgraded.
	// `Deny` (default) means never allow downgrades (thus, never fetch components with a
	// version lower than the version currently deployed).
	// `Allow` means always allow downgrades.
	DowngradePolicy *apiv1alpha1.DowngradePolicy `json:"downgradePolicy,omitempty"`
	// Semver defines the constraint of the fetched version. '>=v0.1'.
	Semver *string `json:"semver,omitempty"`
	// SemverFilter is a regex pattern to filter the versions within the Semver
	// range.
	SemverFilter *string `json:"semverFilter,omitempty"`
	// Verify contains a signature name specifying the component signature to be
	// verified as well as the trusted public keys (or certificates containing
	// the public keys) used to verify the signature.
	Verify []VerificationApplyConfiguration `json:"verify,omitempty"`
	// OCMConfig defines references to secrets, config maps or ocm api
	// objects providing configuration data including credentials.
	OCMConfig []OCMConfigurationApplyConfiguration `json:"ocmConfig,omitempty"`
	// Interval at which the repository will be checked for new component
	// versions.
	Interval *metav1.Duration `json:"interval,omitempty"`
	// Suspend tells the controller to suspend the reconciliation of this
	// Component.
	Suspend *bool `json:"suspend,omitempty"`
}

// ComponentSpecApplyConfiguration constructs a declarative configuration of the ComponentSpec type for use with
// apply.
func ComponentSpec() *ComponentSpecApplyConfiguration {
	return &ComponentSpecApplyConfiguration{}
}

// WithRepositoryRef sets the RepositoryRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepositoryRef field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithRepositoryRef(value v1.LocalObjectReference) *ComponentSpecApplyConfiguration {
	b.RepositoryRef = &value
	return b
}

// WithComponent sets the Component field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Component field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithComponent(value string) *ComponentSpecApplyConfiguration {
	b.Component = &value
	return b
}

// WithDowngradePolicy sets the DowngradePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DowngradePolicy field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithDowngradePolicy(value apiv1alpha1.DowngradePolicy) *ComponentSpecApplyConfiguration {
	b.DowngradePolicy = &value
	return b
}

// WithSemver sets the Semver field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Semver field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithSemver(value string) *ComponentSpecApplyConfiguration {
	b.Semver = &value
	return b
}

// WithSemverFilter sets the SemverFilter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SemverFilter field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithSemverFilter(value string) *ComponentSpecApplyConfiguration {
	b.SemverFilter = &value
	return b
}

// WithVerify adds the given value to the Verify field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Verify field.
func (b *ComponentSpecApplyConfiguration) WithVerify(values ...*VerificationApplyConfiguration) *ComponentSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVerify")
		}
		b.Verify = append(b.Verify, *values[i])
	}
	return b
}

// WithOCMConfig adds the given value to the OCMConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OCMConfig field.
func (b *ComponentSpecApplyConfiguration) WithOCMConfig(values ...*OCMConfigurationApplyConfiguration) *ComponentSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOCMConfig")
		}
		b.OCMConfig = append(b.OCMConfig, *values[i])
	}
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithInterval(value metav1.Duration) *ComponentSpecApplyConfiguration {
	b.Interval = &value
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithSuspend(value bool) *ComponentSpecApplyConfiguration {
	b.Suspend = &value
	return b
}
