// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ComponentStatusApplyConfiguration represents a declarative configuration of the ComponentStatus type for use
// with apply.
//
// ComponentStatus defines the observed state of Component.
type ComponentStatusApplyConfiguration struct {
	// ObservedGeneration is the last observed generation of the ComponentStatus
	// object.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions holds the conditions for the Component.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// Component specifies the concrete version of the component that was
	// fetched after based on the semver constraints during the last successful
	// reconciliation.
	Component *ComponentInfoApplyConfiguration `json:"component,omitempty"`
	// EffectiveOCMConfig specifies the entirety of config maps and secrets
	// whose configuration data was applied to the Component reconciliation,
	// in the order the configuration data was applied.
	EffectiveOCMConfig []OCMConfigurationApplyConfiguration `json:"effectiveOCMConfig,omitempty"`
}

// ComponentStatusApplyConfiguration constructs a declarative configuration of the ComponentStatus type for use with
// apply.
func ComponentStatus() *ComponentStatusApplyConfiguration {
	return &ComponentStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithObservedGeneration(value int64) *ComponentStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ComponentStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ComponentStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithComponent sets the Component field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Component field is set to the value of the last call.
func (b *ComponentStatusApplyConfiguration) WithComponent(value *ComponentInfoApplyConfiguration) *ComponentStatusApplyConfiguration {
	b.Component = value
	return b
}

// WithEffectiveOCMConfig adds the given value to the EffectiveOCMConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EffectiveOCMConfig field.
func (b *ComponentStatusApplyConfiguration) WithEffectiveOCMConfig(values ...*OCMConfigurationApplyConfiguration) *ComponentStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEffectiveOCMConfig")
		}
		b.EffectiveOCMConfig = append(b.EffectiveOCMConfig, *values[i])
	}
	return b
}
