// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// DeployerSpecApplyConfiguration represents a declarative configuration of the DeployerSpec type for use
// with apply.
//
// DeployerSpec defines the desired state of Deployer.
type DeployerSpecApplyConfiguration struct {
	// ResourceRef is the k8s resource name of an OCM resource containing the ResourceGroupDefinition.
	ResourceRef *ObjectKeyApplyConfiguration `json:"resourceRef,omitempty"`
	// OCMConfig defines references to secrets, config maps or ocm api
	// objects providing configuration data including credentials.
	OCMConfig []OCMConfigurationApplyConfiguration `json:"ocmConfig,omitempty"`
	// Suspend tells the controller to suspend the reconciliation of this
	// Resource.
	Suspend *bool `json:"suspend,omitempty"`
}

// DeployerSpecApplyConfiguration constructs a declarative configuration of the DeployerSpec type for use with
// apply.
func DeployerSpec() *DeployerSpecApplyConfiguration {
	return &DeployerSpecApplyConfiguration{}
}

// WithResourceRef sets the ResourceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceRef field is set to the value of the last call.
func (b *DeployerSpecApplyConfiguration) WithResourceRef(value *ObjectKeyApplyConfiguration) *DeployerSpecApplyConfiguration {
	b.ResourceRef = value
	return b
}

// WithOCMConfig adds the given value to the OCMConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OCMConfig field.
func (b *DeployerSpecApplyConfiguration) WithOCMConfig(values ...*OCMConfigurationApplyConfiguration) *DeployerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOCMConfig")
		}
		b.OCMConfig = append(b.OCMConfig, *values[i])
	}
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *DeployerSpecApplyConfiguration) WithSuspend(value bool) *DeployerSpecApplyConfiguration {
	b.Suspend = &value
	return b
}
