// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// DeployedObjectReferenceApplyConfiguration represents a declarative configuration of the DeployedObjectReference type for use
// with apply.
//
// DeployedObjectReference is a reference to an object that has been deployed by the Deployer.
// It contains the API version, kind, name, and optionally the namespace of the deployed object.
type DeployedObjectReferenceApplyConfiguration struct {
	// API version of the referent.
	APIVersion *string `json:"apiVersion,omitempty"`
	// Kind of the referent.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`
	// Name of the referent.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Namespace of the referent.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
	Namespace *string `json:"namespace,omitempty"`
	// UID of the referent.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids
	UID *types.UID `json:"uid,omitempty"`
}

// DeployedObjectReferenceApplyConfiguration constructs a declarative configuration of the DeployedObjectReference type for use with
// apply.
func DeployedObjectReference() *DeployedObjectReferenceApplyConfiguration {
	return &DeployedObjectReferenceApplyConfiguration{}
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *DeployedObjectReferenceApplyConfiguration) WithAPIVersion(value string) *DeployedObjectReferenceApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *DeployedObjectReferenceApplyConfiguration) WithKind(value string) *DeployedObjectReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DeployedObjectReferenceApplyConfiguration) WithName(value string) *DeployedObjectReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *DeployedObjectReferenceApplyConfiguration) WithNamespace(value string) *DeployedObjectReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *DeployedObjectReferenceApplyConfiguration) WithUID(value types.UID) *DeployedObjectReferenceApplyConfiguration {
	b.UID = &value
	return b
}
