// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DeployerStatusApplyConfiguration represents a declarative configuration of the DeployerStatus type for use
// with apply.
//
// DeployerStatus defines the observed state of Deployer.
type DeployerStatusApplyConfiguration struct {
	// ObservedGeneration is the last observed generation of the Deployer
	// object.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions holds the conditions for the Deployer.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// EffectiveOCMConfig specifies the entirety of config maps and secrets
	// whose configuration data was applied to the Resource reconciliation,
	// in the order the configuration data was applied.
	EffectiveOCMConfig []OCMConfigurationApplyConfiguration `json:"effectiveOCMConfig,omitempty"`
	// Deployed contains references to the objects that have been deployed by the Deployer through
	// the Resource.
	Deployed []DeployedObjectReferenceApplyConfiguration `json:"deployed,omitempty"`
}

// DeployerStatusApplyConfiguration constructs a declarative configuration of the DeployerStatus type for use with
// apply.
func DeployerStatus() *DeployerStatusApplyConfiguration {
	return &DeployerStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *DeployerStatusApplyConfiguration) WithObservedGeneration(value int64) *DeployerStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DeployerStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *DeployerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithEffectiveOCMConfig adds the given value to the EffectiveOCMConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EffectiveOCMConfig field.
func (b *DeployerStatusApplyConfiguration) WithEffectiveOCMConfig(values ...*OCMConfigurationApplyConfiguration) *DeployerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEffectiveOCMConfig")
		}
		b.EffectiveOCMConfig = append(b.EffectiveOCMConfig, *values[i])
	}
	return b
}

// WithDeployed adds the given value to the Deployed field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Deployed field.
func (b *DeployerStatusApplyConfiguration) WithDeployed(values ...*DeployedObjectReferenceApplyConfiguration) *DeployerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDeployed")
		}
		b.Deployed = append(b.Deployed, *values[i])
	}
	return b
}
