// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// LabelApplyConfiguration represents a declarative configuration of the Label type for use
// with apply.
type LabelApplyConfiguration struct {
	// Name is the unique name of the label.
	Name *string `json:"name,omitempty"`
	// Value is the json/yaml data of the label
	Value *v1.JSON `json:"value,omitempty"`
	// Version is the optional specification version of the attribute value
	Version *string `json:"version,omitempty"`
	// Signing describes whether the label should be included into the signature
	Signing *bool `json:"signing,omitempty"`
	// MergeAlgorithm optionally describes the desired merge handling used to
	// merge the label value during a transfer.
	Merge *MergeAlgorithmSpecificationApplyConfiguration `json:"merge,omitempty"`
}

// LabelApplyConfiguration constructs a declarative configuration of the Label type for use with
// apply.
func Label() *LabelApplyConfiguration {
	return &LabelApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LabelApplyConfiguration) WithName(value string) *LabelApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *LabelApplyConfiguration) WithValue(value v1.JSON) *LabelApplyConfiguration {
	b.Value = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *LabelApplyConfiguration) WithVersion(value string) *LabelApplyConfiguration {
	b.Version = &value
	return b
}

// WithSigning sets the Signing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Signing field is set to the value of the last call.
func (b *LabelApplyConfiguration) WithSigning(value bool) *LabelApplyConfiguration {
	b.Signing = &value
	return b
}

// WithMerge sets the Merge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Merge field is set to the value of the last call.
func (b *LabelApplyConfiguration) WithMerge(value *MergeAlgorithmSpecificationApplyConfiguration) *LabelApplyConfiguration {
	b.Merge = value
	return b
}
