// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// MergeAlgorithmSpecificationApplyConfiguration represents a declarative configuration of the MergeAlgorithmSpecification type for use
// with apply.
type MergeAlgorithmSpecificationApplyConfiguration struct {
	// Algorithm optionally described the Merge algorithm used to
	// merge the label value during a transfer.
	Algorithm *string `json:"algorithm,omitempty"`
	// Config contains optional config for the merge algorithm.
	Config *v1.JSON `json:"config,omitempty"`
}

// MergeAlgorithmSpecificationApplyConfiguration constructs a declarative configuration of the MergeAlgorithmSpecification type for use with
// apply.
func MergeAlgorithmSpecification() *MergeAlgorithmSpecificationApplyConfiguration {
	return &MergeAlgorithmSpecificationApplyConfiguration{}
}

// WithAlgorithm sets the Algorithm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Algorithm field is set to the value of the last call.
func (b *MergeAlgorithmSpecificationApplyConfiguration) WithAlgorithm(value string) *MergeAlgorithmSpecificationApplyConfiguration {
	b.Algorithm = &value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *MergeAlgorithmSpecificationApplyConfiguration) WithConfig(value v1.JSON) *MergeAlgorithmSpecificationApplyConfiguration {
	b.Config = &value
	return b
}
