// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// NamespacedObjectKindReferenceApplyConfiguration represents a declarative configuration of the NamespacedObjectKindReference type for use
// with apply.
//
// NamespacedObjectKindReference contains enough information to locate the typed referenced Kubernetes resource object
// in any namespace.
type NamespacedObjectKindReferenceApplyConfiguration struct {
	// API version of the referent, if not specified the Kubernetes preferred version will be used.
	APIVersion *string `json:"apiVersion,omitempty"`
	// Kind of the referent.
	Kind *string `json:"kind,omitempty"`
	// Name of the referent.
	Name *string `json:"name,omitempty"`
	// Namespace of the referent, when not specified it acts as LocalObjectReference.
	Namespace *string `json:"namespace,omitempty"`
}

// NamespacedObjectKindReferenceApplyConfiguration constructs a declarative configuration of the NamespacedObjectKindReference type for use with
// apply.
func NamespacedObjectKindReference() *NamespacedObjectKindReferenceApplyConfiguration {
	return &NamespacedObjectKindReferenceApplyConfiguration{}
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *NamespacedObjectKindReferenceApplyConfiguration) WithAPIVersion(value string) *NamespacedObjectKindReferenceApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *NamespacedObjectKindReferenceApplyConfiguration) WithKind(value string) *NamespacedObjectKindReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NamespacedObjectKindReferenceApplyConfiguration) WithName(value string) *NamespacedObjectKindReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *NamespacedObjectKindReferenceApplyConfiguration) WithNamespace(value string) *NamespacedObjectKindReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}
