// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// ObjectKeyApplyConfiguration represents a declarative configuration of the ObjectKey type for use
// with apply.
type ObjectKeyApplyConfiguration struct {
	Namespace *string `json:"namespace,omitempty"`
	Name      *string `json:"name,omitempty"`
}

// ObjectKeyApplyConfiguration constructs a declarative configuration of the ObjectKey type for use with
// apply.
func ObjectKey() *ObjectKeyApplyConfiguration {
	return &ObjectKeyApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ObjectKeyApplyConfiguration) WithNamespace(value string) *ObjectKeyApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ObjectKeyApplyConfiguration) WithName(value string) *ObjectKeyApplyConfiguration {
	b.Name = &value
	return b
}
