// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "ocm.software/open-component-model/kubernetes/controller/api/v1alpha1"
)

// OCMConfigurationApplyConfiguration represents a declarative configuration of the OCMConfiguration type for use
// with apply.
//
// OCMConfiguration defines a configuration applied to the reconciliation of an
// ocm k8s object as well as the policy for its propagation of this
// configuration.
type OCMConfigurationApplyConfiguration struct {
	// Ref reference config maps or secrets containing arbitrary
	// ocm config data (in the ocm config file format), or other configurable
	// ocm api objects (Repository, Component, Resource) to
	// reuse their propagated configuration.
	NamespacedObjectKindReferenceApplyConfiguration `json:",inline"`
	// Policy affects the propagation behavior of the configuration. If set to
	// ConfigurationPolicyPropagate other ocm api objects can reference this
	// object to reuse this configuration.
	Policy *apiv1alpha1.ConfigurationPolicy `json:"policy,omitempty"`
}

// OCMConfigurationApplyConfiguration constructs a declarative configuration of the OCMConfiguration type for use with
// apply.
func OCMConfiguration() *OCMConfigurationApplyConfiguration {
	return &OCMConfigurationApplyConfiguration{}
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *OCMConfigurationApplyConfiguration) WithAPIVersion(value string) *OCMConfigurationApplyConfiguration {
	b.NamespacedObjectKindReferenceApplyConfiguration.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *OCMConfigurationApplyConfiguration) WithKind(value string) *OCMConfigurationApplyConfiguration {
	b.NamespacedObjectKindReferenceApplyConfiguration.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *OCMConfigurationApplyConfiguration) WithName(value string) *OCMConfigurationApplyConfiguration {
	b.NamespacedObjectKindReferenceApplyConfiguration.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *OCMConfigurationApplyConfiguration) WithNamespace(value string) *OCMConfigurationApplyConfiguration {
	b.NamespacedObjectKindReferenceApplyConfiguration.Namespace = &value
	return b
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *OCMConfigurationApplyConfiguration) WithPolicy(value apiv1alpha1.ConfigurationPolicy) *OCMConfigurationApplyConfiguration {
	b.Policy = &value
	return b
}
