// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RepositoryStatusApplyConfiguration represents a declarative configuration of the RepositoryStatus type for use
// with apply.
//
// RepositoryStatus defines the observed state of Repository.
type RepositoryStatusApplyConfiguration struct {
	// ObservedGeneration is the last observed generation of the Repository
	// object.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions holds the conditions for the Repository.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// EffectiveOCMConfig specifies the entirety of config maps and secrets
	// whose configuration data was applied to the Repository reconciliation,
	// in the order the configuration data was applied.
	EffectiveOCMConfig []OCMConfigurationApplyConfiguration `json:"effectiveOCMConfig,omitempty"`
}

// RepositoryStatusApplyConfiguration constructs a declarative configuration of the RepositoryStatus type for use with
// apply.
func RepositoryStatus() *RepositoryStatusApplyConfiguration {
	return &RepositoryStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *RepositoryStatusApplyConfiguration) WithObservedGeneration(value int64) *RepositoryStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RepositoryStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *RepositoryStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithEffectiveOCMConfig adds the given value to the EffectiveOCMConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EffectiveOCMConfig field.
func (b *RepositoryStatusApplyConfiguration) WithEffectiveOCMConfig(values ...*OCMConfigurationApplyConfiguration) *RepositoryStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEffectiveOCMConfig")
		}
		b.EffectiveOCMConfig = append(b.EffectiveOCMConfig, *values[i])
	}
	return b
}
