// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RepositorySpecApplyConfiguration represents a declarative configuration of the RepositorySpec type for use
// with apply.
//
// RepositorySpec defines the desired state of Repository.
type RepositorySpecApplyConfiguration struct {
	// RepositorySpec is the config of an ocm repository containing component
	// versions. This config has to be a valid ocm repository implementation
	// specification
	// https://github.com/open-component-model/ocm-spec/blob/main/doc/04-extensions/03-storage-backends/README.md.
	RepositorySpec *v1.JSON `json:"repositorySpec,omitempty"`
	// OCMConfig defines references to secrets, config maps or ocm api
	// objects providing configuration data including credentials.
	OCMConfig []OCMConfigurationApplyConfiguration `json:"ocmConfig,omitempty"`
	// Interval at which the ocm repository specified by the RepositorySpec
	// validated.
	Interval *metav1.Duration `json:"interval,omitempty"`
	// Suspend tells the controller to suspend the reconciliation of this
	// Repository.
	Suspend *bool `json:"suspend,omitempty"`
}

// RepositorySpecApplyConfiguration constructs a declarative configuration of the RepositorySpec type for use with
// apply.
func RepositorySpec() *RepositorySpecApplyConfiguration {
	return &RepositorySpecApplyConfiguration{}
}

// WithRepositorySpec sets the RepositorySpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepositorySpec field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithRepositorySpec(value v1.JSON) *RepositorySpecApplyConfiguration {
	b.RepositorySpec = &value
	return b
}

// WithOCMConfig adds the given value to the OCMConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OCMConfig field.
func (b *RepositorySpecApplyConfiguration) WithOCMConfig(values ...*OCMConfigurationApplyConfiguration) *RepositorySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOCMConfig")
		}
		b.OCMConfig = append(b.OCMConfig, *values[i])
	}
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithInterval(value metav1.Duration) *RepositorySpecApplyConfiguration {
	b.Interval = &value
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithSuspend(value bool) *RepositorySpecApplyConfiguration {
	b.Suspend = &value
	return b
}
