// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apiv1alpha1 "ocm.software/open-component-model/kubernetes/controller/api/v1alpha1"
)

// ResourceSpecApplyConfiguration represents a declarative configuration of the ResourceSpec type for use
// with apply.
//
// ResourceSpec defines the desired state of Resource.
type ResourceSpecApplyConfiguration struct {
	// ComponentRef is a reference to a Component.
	ComponentRef *v1.LocalObjectReference `json:"componentRef,omitempty"`
	// Resource identifies the ocm resource to be fetched.
	Resource *ResourceIDApplyConfiguration `json:"resource,omitempty"`
	// OCMConfig defines references to secrets, config maps or ocm api
	// objects providing configuration data including credentials.
	OCMConfig []OCMConfigurationApplyConfiguration `json:"ocmConfig,omitempty"`
	// VerificationPolicy controls when resource digest verification is performed.
	// Always (default): attempt to verify resource digest; if no processor plugin is found, log and continue.
	// Never: skip verification unconditionally.
	VerificationPolicy *apiv1alpha1.VerificationPolicy `json:"verificationPolicy,omitempty"`
	// Interval at which the resource is checked for updates.
	Interval *metav1.Duration `json:"interval,omitempty"`
	// Suspend tells the controller to suspend the reconciliation of this
	// Resource.
	Suspend *bool `json:"suspend,omitempty"`
	// AdditionalStatusFields are additional fields that can be used to
	// extend the status of the Resource with custom expressions.
	// Values can be either CEL expression strings or nested objects
	// containing CEL expression strings.
	AdditionalStatusFields *apiextensionsv1.JSON `json:"additionalStatusFields,omitempty"`
}

// ResourceSpecApplyConfiguration constructs a declarative configuration of the ResourceSpec type for use with
// apply.
func ResourceSpec() *ResourceSpecApplyConfiguration {
	return &ResourceSpecApplyConfiguration{}
}

// WithComponentRef sets the ComponentRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ComponentRef field is set to the value of the last call.
func (b *ResourceSpecApplyConfiguration) WithComponentRef(value v1.LocalObjectReference) *ResourceSpecApplyConfiguration {
	b.ComponentRef = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *ResourceSpecApplyConfiguration) WithResource(value *ResourceIDApplyConfiguration) *ResourceSpecApplyConfiguration {
	b.Resource = value
	return b
}

// WithOCMConfig adds the given value to the OCMConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OCMConfig field.
func (b *ResourceSpecApplyConfiguration) WithOCMConfig(values ...*OCMConfigurationApplyConfiguration) *ResourceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOCMConfig")
		}
		b.OCMConfig = append(b.OCMConfig, *values[i])
	}
	return b
}

// WithVerificationPolicy sets the VerificationPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VerificationPolicy field is set to the value of the last call.
func (b *ResourceSpecApplyConfiguration) WithVerificationPolicy(value apiv1alpha1.VerificationPolicy) *ResourceSpecApplyConfiguration {
	b.VerificationPolicy = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *ResourceSpecApplyConfiguration) WithInterval(value metav1.Duration) *ResourceSpecApplyConfiguration {
	b.Interval = &value
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *ResourceSpecApplyConfiguration) WithSuspend(value bool) *ResourceSpecApplyConfiguration {
	b.Suspend = &value
	return b
}

// WithAdditionalStatusFields sets the AdditionalStatusFields field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdditionalStatusFields field is set to the value of the last call.
func (b *ResourceSpecApplyConfiguration) WithAdditionalStatusFields(value apiextensionsv1.JSON) *ResourceSpecApplyConfiguration {
	b.AdditionalStatusFields = &value
	return b
}
