// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ResourceStatusApplyConfiguration represents a declarative configuration of the ResourceStatus type for use
// with apply.
//
// ResourceStatus defines the observed state of Resource.
type ResourceStatusApplyConfiguration struct {
	// ObservedGeneration is the last observed generation of the Resource
	// object.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions holds the conditions for the Resource.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	Resource   *ResourceInfoApplyConfiguration  `json:"resource,omitempty"`
	Component  *ComponentInfoApplyConfiguration `json:"component,omitempty"`
	// EffectiveOCMConfig specifies the entirety of config maps and secrets
	// whose configuration data was applied to the Resource reconciliation,
	// in the order the configuration data was applied.
	EffectiveOCMConfig []OCMConfigurationApplyConfiguration `json:"effectiveOCMConfig,omitempty"`
	Additional         *apiextensionsv1.JSON                `json:"additional,omitempty"`
}

// ResourceStatusApplyConfiguration constructs a declarative configuration of the ResourceStatus type for use with
// apply.
func ResourceStatus() *ResourceStatusApplyConfiguration {
	return &ResourceStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ResourceStatusApplyConfiguration) WithObservedGeneration(value int64) *ResourceStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ResourceStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *ResourceStatusApplyConfiguration) WithResource(value *ResourceInfoApplyConfiguration) *ResourceStatusApplyConfiguration {
	b.Resource = value
	return b
}

// WithComponent sets the Component field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Component field is set to the value of the last call.
func (b *ResourceStatusApplyConfiguration) WithComponent(value *ComponentInfoApplyConfiguration) *ResourceStatusApplyConfiguration {
	b.Component = value
	return b
}

// WithEffectiveOCMConfig adds the given value to the EffectiveOCMConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EffectiveOCMConfig field.
func (b *ResourceStatusApplyConfiguration) WithEffectiveOCMConfig(values ...*OCMConfigurationApplyConfiguration) *ResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEffectiveOCMConfig")
		}
		b.EffectiveOCMConfig = append(b.EffectiveOCMConfig, *values[i])
	}
	return b
}

// WithAdditional sets the Additional field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Additional field is set to the value of the last call.
func (b *ResourceStatusApplyConfiguration) WithAdditional(value apiextensionsv1.JSON) *ResourceStatusApplyConfiguration {
	b.Additional = &value
	return b
}
