// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// ResourceReferenceApplyConfiguration represents a declarative configuration of the ResourceReference type for use
// with apply.
//
// ResourceReference defines a reference to a resource akin to the OCM Specification.
// For more details see dedicated guide in the Specification:
// https://github.com/open-component-model/ocm-spec/blob/main/doc/05-guidelines/03-references.md#references
type ResourceReferenceApplyConfiguration struct {
	Resource      *runtime.Identity  `json:"resource,omitempty"`
	ReferencePath []runtime.Identity `json:"referencePath,omitempty"`
}

// ResourceReferenceApplyConfiguration constructs a declarative configuration of the ResourceReference type for use with
// apply.
func ResourceReference() *ResourceReferenceApplyConfiguration {
	return &ResourceReferenceApplyConfiguration{}
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *ResourceReferenceApplyConfiguration) WithResource(value runtime.Identity) *ResourceReferenceApplyConfiguration {
	b.Resource = &value
	return b
}

// WithReferencePath adds the given value to the ReferencePath field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ReferencePath field.
func (b *ResourceReferenceApplyConfiguration) WithReferencePath(values ...runtime.Identity) *ResourceReferenceApplyConfiguration {
	for i := range values {
		b.ReferencePath = append(b.ReferencePath, values[i])
	}
	return b
}
