// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// ResourceIDApplyConfiguration represents a declarative configuration of the ResourceID type for use
// with apply.
//
// ResourceID defines the configuration of the repository.
type ResourceIDApplyConfiguration struct {
	ByReference *ResourceReferenceApplyConfiguration `json:"byReference,omitempty"`
}

// ResourceIDApplyConfiguration constructs a declarative configuration of the ResourceID type for use with
// apply.
func ResourceID() *ResourceIDApplyConfiguration {
	return &ResourceIDApplyConfiguration{}
}

// WithByReference sets the ByReference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ByReference field is set to the value of the last call.
func (b *ResourceIDApplyConfiguration) WithByReference(value *ResourceReferenceApplyConfiguration) *ResourceIDApplyConfiguration {
	b.ByReference = value
	return b
}
