// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
)

// ResourceInfoApplyConfiguration represents a declarative configuration of the ResourceInfo type for use
// with apply.
type ResourceInfoApplyConfiguration struct {
	Name          *string                   `json:"name,omitempty"`
	Type          *string                   `json:"type,omitempty"`
	Version       *string                   `json:"version,omitempty"`
	ExtraIdentity map[string]string         `json:"extraIdentity,omitempty"`
	Access        *v1.JSON                  `json:"access,omitempty"`
	Digest        *v2.Digest                `json:"digest,omitempty"`
	Labels        []LabelApplyConfiguration `json:"labels,omitempty"`
}

// ResourceInfoApplyConfiguration constructs a declarative configuration of the ResourceInfo type for use with
// apply.
func ResourceInfo() *ResourceInfoApplyConfiguration {
	return &ResourceInfoApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ResourceInfoApplyConfiguration) WithName(value string) *ResourceInfoApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ResourceInfoApplyConfiguration) WithType(value string) *ResourceInfoApplyConfiguration {
	b.Type = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ResourceInfoApplyConfiguration) WithVersion(value string) *ResourceInfoApplyConfiguration {
	b.Version = &value
	return b
}

// WithExtraIdentity puts the entries into the ExtraIdentity field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExtraIdentity field,
// overwriting an existing map entries in ExtraIdentity field with the same key.
func (b *ResourceInfoApplyConfiguration) WithExtraIdentity(entries map[string]string) *ResourceInfoApplyConfiguration {
	if b.ExtraIdentity == nil && len(entries) > 0 {
		b.ExtraIdentity = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ExtraIdentity[k] = v
	}
	return b
}

// WithAccess sets the Access field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Access field is set to the value of the last call.
func (b *ResourceInfoApplyConfiguration) WithAccess(value v1.JSON) *ResourceInfoApplyConfiguration {
	b.Access = &value
	return b
}

// WithDigest sets the Digest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Digest field is set to the value of the last call.
func (b *ResourceInfoApplyConfiguration) WithDigest(value v2.Digest) *ResourceInfoApplyConfiguration {
	b.Digest = &value
	return b
}

// WithLabels adds the given value to the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Labels field.
func (b *ResourceInfoApplyConfiguration) WithLabels(values ...*LabelApplyConfiguration) *ResourceInfoApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithLabels")
		}
		b.Labels = append(b.Labels, *values[i])
	}
	return b
}
