// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// VerificationApplyConfiguration represents a declarative configuration of the Verification type for use
// with apply.
type VerificationApplyConfiguration struct {
	// Signature defines the name of the signature to be verified in the component version.
	Signature *string `json:"signature,omitempty"`
	// Public Key Secret Format
	// A secret containing public keys for signature verification is expected to be of the structure:
	//
	// Data:
	// <Signature-Name>: <PublicKey/Certificate>
	//
	// Additionally, to prepare for a common ocm secret management, it might make sense to introduce a specific secret type
	// for these secrets.
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
	// Value defines a PEM/base64 encoded public key value.
	Value *string `json:"value,omitempty"`
}

// VerificationApplyConfiguration constructs a declarative configuration of the Verification type for use with
// apply.
func Verification() *VerificationApplyConfiguration {
	return &VerificationApplyConfiguration{}
}

// WithSignature sets the Signature field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Signature field is set to the value of the last call.
func (b *VerificationApplyConfiguration) WithSignature(value string) *VerificationApplyConfiguration {
	b.Signature = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *VerificationApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *VerificationApplyConfiguration {
	b.SecretRef = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *VerificationApplyConfiguration) WithValue(value string) *VerificationApplyConfiguration {
	b.Value = &value
	return b
}
