name: Kubernetes Controller
on:
  push:
    branches:
      - main
    paths:
      - kubernetes/controller/**/*
  pull_request:
    branches:
      - main
    paths:
      - kubernetes/controller/**/*

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  E2E:
    name: E2E
    runs-on: large_runner
    steps:
      - name: Self Hosted Runner Post Job Cleanup Action
        uses: TooMuch4U/actions-clean@9b358e33df99574ac0bdf2e92fa3db1ae1415563 # v2.2

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go (required for CLI build)
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: kubernetes/controller/go.mod
          cache-dependency-path: kuberneetes/controller/go.sum

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker
        uses: docker/setup-docker-action@v4

      - name: Setup ocm
        uses: open-component-model/ocm-setup-action@655f3525fd283ca7d22e6b2ceec42324331df401 # v1.0.0

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@6bf37f6a560fd84982d67f853162e4b3c2235edb # v2.6.4

      - name: Setup
        run: task kubernetes/controller:test/e2e/setup/local

      - name: Run
        run: task kubernetes/controller:test/e2e
