name: Latest

on:
  workflow_run:
    workflows: [ "Kubernetes Controller" ]        # name of the workflow that must complete
    types:
      - completed


concurrency:
  group: publish-latest-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish-controller:
    name: Controller Image
    if: ${{
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == github.event.repository.default_branch &&
      github.event.workflow.name == 'Kubernetes Controller' }}
    runs-on: large_runner
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          sparse-checkout: |
            kubernetes/controller
            .github/workflows/kubernetes-controller.yml
            Taskfile.yml
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Multi-Arch
        run: task kubernetes/controller:docker-build/multi-arch PUSH=true
